{
 "title": "13001 监控",
 "time": { "from": "2019-07-28T08:44:03.488Z", "to": "2019-07-28T13:47:15.656Z" },
 "templating": {
  "list": [
   {
    "name": "url",
    "label": "url",
    "query": "label_values(namelookup_time{job=\"prometheus\"},url)"
   }
  ]
 },
 "panels": [
  {
   "title": "total_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "total_time{job=\"prometheus\", url=\"$url\"}"
    }
   ]
  },
  {
   "title": "DNS time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "namelookup_time{job=\"prometheus\", url=\"$url\"}"
    }
   ]
  },
  {
   "title": "speed_download",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "speed_download{job=\"prometheus\", url=\"$url\"}"
    }
   ]
  },
  {
   "title": "connect time ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "connect_time{job=\"prometheus\", url=\"$url\"}"
    }
   ]
  },
  {
   "title": "start_transfer_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "starttransfer_time{job=\"prometheus\", url=\"$url\"}"
    }
   ]
  },
  {
   "title": "pretransfer_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "pretransfer_time{job=\"prometheus\", url=\"$url\"}"
    }
   ]
  }
 ]
}